# Update interconnection FYI data and validate against LBNL + GridStatus data

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import dbcp
from dbcp.extract.helpers import cache_gcs_archive_file_locally
from dbcp.helpers import get_sql_engine

from dbcp.constants import DATA_DIR
from dbcp.extract.helpers import load_yml_file

In [3]:
pd.set_option('display.max_columns', None)

# Raw Data

In [4]:
old_fyi = dbcp.extract.fyi_queue.extract("gs://dgm-archive/interconnection.fyi/interconnection_fyi_dataset_2026-07-01.csv")
old_fyi = old_fyi["fyi_queue"]

/app/src/dbcp/extract/fyi_queue.py:19: DtypeWarning: Columns (42,43) have mixed types. Specify dtype option on import or set low_memory=False.
  all_projects = pd.read_csv(path)

In [5]:
file_paths = load_yml_file(DATA_DIR / "file_paths.yml")

new_fyi = dbcp.extract.fyi_queue.extract(file_paths['fyi_queue'].item())
new_fyi = new_fyi["fyi_queue"]

/app/src/dbcp/extract/fyi_queue.py:19: DtypeWarning: Columns (42,43) have mixed types. Specify dtype option on import or set low_memory=False.
  all_projects = pd.read_csv(path)

,unique_id,project_type,power_market,transmission_owner,canonical_transmission_owners,queue_id,project_name,actual_completion_date,proposed_completion_date,withdrawn_date,...,gis_longitude,gis_lat_long_specificity,capacity_by_generation_type_breakdown,interconnection_voltage_kv,fips_codes,schedule_next_event_date,schedule_next_event_name,most_recent_study_date,most_recent_allocated_network_upgrade_cost,most_recent_study_url
0,aeso-p1828,Generation,AESO,Alberta Electric System Operator,Alberta Electric System Operator,P1828,P1828 hep Energy Alderson MPC Solar,NaN,2027-06-03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,aeso-p2034,Generation,AESO,Alberta Electric System Operator,Alberta Electric System Operator,P2034,P2034 Cold Lake Energy (Lindbergh Cogeneration),NaN,2029-10-01,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,aeso-p2091,Generation,AESO,Alberta Electric System Operator,Alberta Electric System Operator,P2091,P2091 Arenosum Solar,NaN,2028-05-26,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,aeso-p2192,Generation,AESO,Alberta Electric System Operator,Alberta Electric System Operator,P2192,P2192 ENMAX FMC Change,NaN,2026-10-04,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,aeso-p2195,Generation,AESO,Alberta Electric System Operator,Alberta Electric System Operator,P2195,P2195 FortisAlberta Bassano 435S DER Solar,NaN,2027-06-01,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42938,wapa-ti-1001,Transmission,West,WAPA/BEPC/HCPD Integrated System,WAPA/BEPC/HCPD Integrated System,TI-1001,NaN,NaN,NaN,NaN,...,-96.306326,poi,NaN,161.0,19193,NaN,NaN,NaN,NaN,NaN
42939,wapa-ti-1301,Transmission,West,WAPA/BEPC/HCPD Integrated System,WAPA/BEPC/HCPD Integrated System,TI-1301,NaN,NaN,NaN,NaN,...,-98.784766,county,NaN,345.0,31089,NaN,NaN,NaN,NaN,NaN
42940,wapa-ti-1302,Transmission,West,WAPA/BEPC/HCPD Integrated System,WAPA/BEPC/HCPD Integrated System,TI-1302,NaN,NaN,NaN,NaN,...,-103.942528,poi,NaN,345.0,31157,NaN,NaN,NaN,NaN,NaN
42941,wapa-ti-1401,Transmission,West,WAPA/BEPC/HCPD Integrated System,WAPA/BEPC/HCPD Integrated System,TI-1401,NaN,NaN,NaN,NaN,...,-96.948690,poi,NaN,115.0,38017,NaN,NaN,NaN,NaN,NaN
42942,wapa-ti-1502,Transmission,West,WAPA/BEPC/HCPD Integrated System,WAPA/BEPC/HCPD Integrated System,TI-1502,NaN,NaN,NaN,NaN,...,-103.284594,poi,NaN,230.0,38053,NaN,NaN,NaN,NaN,NaN

## Compare max dates of raw data
Print out the latest date a project entered a queue for each ISO in the old and new data. We should expect the latest project date in the new data to be larger than the that of the old data. Notable exceptions:
* PJM: PJM [is working through a backlog of projects](https://www.utilitydive.com/news/pjm-fast-track-reliability-projects-interconnection-queue-invenergy/729311/) and isn't accepting new projects until mid 2026.

In [6]:
# any new ISOs?
print(
    f"New ISOs: {list(set(new_fyi.power_market.unique()) - set(old_fyi.power_market.unique()))}\n"
    f"Missing ISOs: {list(set(old_fyi.power_market.unique()) - set(new_fyi.power_market.unique()))}"
)

New ISOs: []
Missing ISOs: []

In [7]:
for power_market in old_fyi.power_market.unique():
    print(power_market)
    old_df = old_fyi[old_fyi.power_market == power_market]
    new_df = new_fyi[new_fyi.power_market == power_market]
    
    old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
    new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])
    
    print(f" - Old max date {old_df['queue_date'].max()}")
    print(f" - New max date {new_df['queue_date'].max()}")
    print()

/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])

AESO
 - Old max date 2026-05-20 00:00:00
 - New max date 2026-05-26 00:00:00

West
 - Old max date 2026-10-21 00:00:00
 - New max date 2026-10-21 00:00:00

Southeast
 - Old max date 2026-06-03 00:00:00
 - New max date 2026-06-25 00:00:00

BC
 - Old max date 2025-10-14 00:00:00
 - New max date 2025-10-14 00:00:00

CAISO
 - Old max date 2025-02-12 00:00:00
 - New max date 2025-02-12 00:00:00

ERCOT
 - Old max date 2026-05-26 00:00:00
 - New max date 2026-06-29 00:00:00

Quebec
 - Old max date NaT
 - New max date NaT

IESO
 - Old max date NaT
 - New max date NaT

ISO-NE
 - Old max date 2025-01-14 00:00:00
 - New max date 2025-01-14 00:00:00

Manitoba
 - Old max date 2025-10-17 00:00:00
 - New max date 2025-10-17 00:00:00

MISO
 - Old max date 2026-06-08 00:00:00
 - New max date 2026-06-25 00:00:00

Maritimes
 - Old max date 2026-05-11 00:00:00
 - New max date 2026-05-11 00:00:00

NYISO
 - Old max date 2026-05-29 00:00:00
 - New max date 2026-05-29 00:00:00

PJM
 - Old max date 2026-02-27 00:00:00
 - New max date 2026-02-27 00:00:00

Saskatchewan
 - Old max date 2025-07-10 00:00:00
 - New max date 2025-07-10 00:00:00

SPP
 - Old max date 2026-05-28 00:00:00
 - New max date 2026-06-26 00:00:00

/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  old_df['queue_date'] = pd.to_datetime(old_df.loc[:, 'queue_date'])
/tmp/ipykernel_27/527979714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['queue_date'] = pd.to_datetime(new_df.loc[:, 'queue_date'])

## Summarize changes

In [8]:
# What were the changes in capacity by queue and status?
new_fyi.groupby(['power_market', 'queue_status'])['capacity_mw'].sum()-old_fyi.groupby(['power_market', 'queue_status'])['capacity_mw'].sum()

power_market  queue_status
AESO          Active           -183.392600
              Operational       -33.022400
              Withdrawn       -1923.900000
BC            Active              0.000000
CAISO         Active         -12381.220000
              Operational       605.200000
              Suspended           0.000000
              Withdrawn       11776.020000
ERCOT         Active           7302.840000
              Operational      1606.710000
              Suspended        -473.410000
              Withdrawn        5233.590000
IESO          Active           -680.960000
              Operational      -132.600000
              Suspended          43.060000
              Withdrawn        1105.000000
ISO-NE        Active           -194.559998
              Operational         0.000000
              Withdrawn         170.000000
MISO          Active           4680.202000
              Operational         0.000000
              Withdrawn         650.440000
Manitoba      Active              0.000000
              Operational         0.000000
Maritimes     Active              0.000000
NYISO         Active           -290.800000
              Operational      -310.000000
              Withdrawn        2085.941989
PJM           Active            151.300000
              Operational       202.700000
              Suspended        -562.900000
              Withdrawn         193.000000
Quebec        Active              0.000000
              Operational         0.000000
SPP           Active           2927.000000
              Operational       908.745000
              Suspended         973.040000
              Withdrawn         624.550000
Saskatchewan  Active              0.000000
Southeast     Active            990.600000
              Operational       -72.500000
              Suspended        -144.200000
              Withdrawn        -155.800000
West          Active          -6536.150000
              Operational      1373.500000
              Suspended        -605.000000
              Unknown          8946.500000
              Withdrawn       13281.550000
Name: capacity_mw, dtype: float64

# Create data warehouse and data mart tables

Update the URI of the archived FYI data in `dbcp.etl.etl_fyi_queue`. Then run `make all` to generate the data warehouse and data mart tables. Debug any errors that arise.

## Compare data warehouse tables to raw data

In [9]:
engine = get_sql_engine()
with engine.connect() as con:
    fyi_locations = pd.read_sql_table("fyi__private__locations", con, schema="data_warehouse")
    fyi_projects = pd.read_sql_table("fyi__private__projects", con, schema="data_warehouse")
    fyi_res_cap = pd.read_sql_table("fyi__private__resource_capacity", con, schema="data_warehouse")

We deduplicate the data so there are project IDs in the raw data that aren't in the data warehouse tables, but ensure that we're not losing an unexpectedly high number. During the creation of the data warehouse tables we log how many projects are dropped because they are found to be duplicates. Make sure that no table is missing many more than that number of IDs. The location table will have more missing IDs because there is more nullness in the location columns than in the capacity columns.

In [10]:
print(len(set(new_fyi.unique_id) - set(fyi_projects.project_id)))
print(len(set(new_fyi.unique_id) - set(fyi_locations.project_id)))
print(len(set(new_fyi.unique_id) - set(fyi_res_cap.project_id)))

3891
4652
3892

## Compare new data mart table to previous version
Compare the old and new total active capacity in regions. At this point we've already produced the data mart table, so we can grab this just like we did the data warehouse tables. To get the old 

<!-- - download the `dev` data to compare to
- load the relevent tables

data warehouse
- check the old and new iso have a similar n and capacity
- plot total capacity


data mart:
- total capacity, n_projects and max date have all the same: caiso, ercot, pjm
- total capacity, n_projects and max date have all increased: miso, pjm, spp, nyiso, isone
- withdrawn and in service capacity have increased: miso, pjm, spp, nyiso, isone

- active capacity has changed for isos in GS_REGIONS
- how much has the active capacity changed by? -->

In [11]:
fyi_active_projects_table_name = "fyi__private__counties__active_clean_projects_capacity"

engine = get_sql_engine()
with engine.connect() as con:
    fyi_projects_active = pd.read_sql_table(fyi_active_projects_table_name, con, schema="data_mart")

### Get previous version of data mart table

In [12]:
from google.cloud import bigquery

def get_bigquery_table(dataset_id, table_name, project_id="dbcp-dev-350818") -> pd.DataFrame:
    """
    Get a dataframe from a BigQuery table.

    Args:
        dataset_id: the BQ dataset ID
        table_name: the name of the table
        project_id: the GCP project id
    """
    client = bigquery.Client()

    table_ref = f"{project_id}.{dataset_id}.{table_name}"
    return client.query(f"SELECT * FROM `{table_ref}`").to_dataframe()

old_fyi_projects_active = get_bigquery_table("data_mart_dev", fyi_active_projects_table_name)

/app/.venv/lib/python3.13/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

In [21]:
# Get detailed diff of both tables
diff_df = fyi_projects_active.merge(old_fyi_projects_active, how='outer', indicator=True)
diff_df[diff_df._merge != 'both']

,county_id_fips,state,county,battery_storage_active_capacity_mw,onshore_wind_active_capacity_mw,offshore_wind_active_capacity_mw,solar_active_capacity_mw,total_active_clean_projects_capacity_mw,_merge
24,04001,Arizona,Apache,412.00,1368.0,NaN,1911.28,3691.28,left_only
25,04001,Arizona,Apache,412.00,1368.0,NaN,2911.28,4691.28,right_only
26,04003,Arizona,Cochise,NaN,200.0,NaN,780.00,980.00,right_only
27,04003,Arizona,Cochise,NaN,200.0,NaN,1080.00,1280.00,left_only
28,04005,Arizona,Coconino,140.00,1109.2,NaN,4350.00,5599.20,right_only
...,...,...,...,...,...,...,...,...,...
1777,53071,Washington,Walla Walla,310.00,402.3,NaN,329.00,1041.30,right_only
1780,53077,Washington,Yakima,1360.50,NaN,NaN,1554.99,2915.49,left_only
1781,53077,Washington,Yakima,1360.50,NaN,NaN,1651.79,3012.29,right_only
1816,55097,Wisconsin,Portage,50.00,NaN,NaN,1196.16,1246.16,right_only
1817,55097,Wisconsin,Portage,50.31,NaN,NaN,1196.18,1246.49,left_only

### Sanity check missing counties / capacity changes
Changes in project status can lead to new counties showing up or counties disappearing from the active projects table. This is normal and expected behavior, but we can do some quick sanity checks to verify that there are no unexpected changes.

In [13]:
combined_active_projects = old_fyi_projects_active.merge(fyi_projects_active, how="outer", on="county_id_fips", indicator=True)
missing_counties = combined_active_projects.loc[combined_active_projects['_merge'] == 'left_only', "county_id_fips"]
new_counties = combined_active_projects.loc[combined_active_projects['_merge'] == 'right_only', "county_id_fips"]

fyi_projects_w_fips = fyi_projects.merge(fyi_locations[fyi_locations["county_id_fips"].notnull()], on="project_id")

First check to see the queue status for all projects contained within the columns that were in the previous version of the active projects table, but no longer are. If there are no active projects, then that alone will explain the changes.

In [14]:
fyi_projects_w_fips.loc[fyi_projects_w_fips["county_id_fips"].isin(missing_counties), "queue_status"].value_counts()

queue_status
withdrawn      64
operational    12
suspended       7
active          1
Name: count, dtype: int64

However, there generally are at least a few active projects within these columns, but if they are not renewable projects, then we would not expect these to show up either. Let's check the generation type of all active projects within the missing columns. If none of these are renewable, then there's nothing to worry about.

In [15]:
fyi_projects_w_fips.loc[
    (fyi_projects_w_fips["county_id_fips"].isin(missing_counties)) & (fyi_projects_w_fips["queue_status"] == "active"),
    "canonical_generation_types"
]

8672    Gas
Name: canonical_generation_types, dtype: object

Next, let's do some similar checks on new counties.

In [16]:
fyi_projects_w_fips.loc[
    (fyi_projects_w_fips["county_id_fips"].isin(new_counties)) & (fyi_projects_w_fips["queue_status"] == "active"),
    "canonical_generation_types"
]

966      Battery + Solar
4873             Battery
4917                 Gas
4987             Battery
5353             Battery
5825                 Gas
8266                 Gas
9117             Battery
9153             Battery
30314         Geothermal
32386               Wind
32558              Solar
32837               Wind
32848              Solar
32853              Solar
32854              Solar
32860    Battery + Solar
32861              Solar
32863              Solar
32867              Solar
32870              Solar
32871              Solar
32873              Solar
32876    Battery + Solar
35534            Battery
35536            Battery
Name: canonical_generation_types, dtype: object